---
# tasks file for mysql

- name: Install mysql
  apt:
    name:
      - mysql-server
      - mysql-client
      - python3-mysqldb
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Set root password
  mysql_user:
    login_user: "{{ admin_user_name }}"
    login_password: "{{ admin_user_password }}"
    name: "{{ admin_user_name }}"
    password: "{{ admin_user_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
    state: present

- name: Remove anonymous user
  mysql_user:
    login_user: "{{ admin_user_name }}"
    login_password: "{{ admin_user_password }}"
    name: ""
    host_all: yes
    state: absent

- name: Set default-character-set
  ini_file:
    path: /etc/mysql/mysql.conf.d/mysql.cnf
    section: mysql
    option: default-character-set
    value: utf8mb4

- name: Set character-set-server
  ini_file:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    section: mysqld
    option: character-set-server
    value: utf8mb4

- name: Create database
  mysql_db:
    login_user: "{{ admin_user_name }}"
    login_password: "{{ admin_user_password }}"
    name: "{{ db_name }}"
    state: present
    encoding: utf8mb4

- name: Add user
  mysql_user:
    login_user: "{{ admin_user_name }}"
    login_password: "{{ admin_user_password }}"
    name: "{{ user_name }}"
    host: "{{ user_host }}"
    password: "{{ user_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present

- name: Set bind-address to allow remote connection
  ini_file:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    section: mysqld
    option: bind-address
    value: 0.0.0.0

- name: Restart mysql
  systemd:
    state: restarted
    name: mysql
    enabled: yes
